<script setup lang="ts">
// AI-assisted: displays compact global-stat records generated by the backend.
import axios from 'axios'
import { computed, onMounted, onUnmounted, ref } from 'vue'

type TickerMatch = {
  date: string
  home: string
  away: string
  homeScore: number
  awayScore: number
  focusTeam: string | null
}

type TickerItem = {
  scope: string
  scopeLabel: string
  from: string
  to: string
  section: string
  sectionLabel: string
  text: string
  value: number
  match: TickerMatch
  link: string
}

type TickerPayload = {
  latestMatchDate: string | null
  currentSeasonStart: string
  items: TickerItem[]
}

const items = ref<TickerItem[]>([])
const currentIndex = ref(0)
let intervalId: number | undefined

const currentItem = computed(() => items.value[currentIndex.value] ?? null)

function pickNextItem() {
  if (items.value.length <= 1) {
    currentIndex.value = 0
    return
  }
  let nextIndex = currentIndex.value
  while (nextIndex === currentIndex.value) {
    nextIndex = Math.floor(Math.random() * items.value.length)
  }
  currentIndex.value = nextIndex
}

onMounted(async () => {
  try {
    const response = await axios.get<TickerPayload>('/global-stat-ticker.json')
    items.value = response.data.items ?? []
    pickNextItem()
    intervalId = window.setInterval(pickNextItem, 9000)
  } catch (error) {
    console.warn('Could not load global stats ticker', error)
  }
})

onUnmounted(() => {
  if (intervalId !== undefined) {
    clearInterval(intervalId)
  }
})
</script>

<template>
  <div v-if="currentItem" class="global-stats-ticker">
    <span class="ticker-label">{{ currentItem.scopeLabel }}</span>
    <router-link :to="currentItem.link">
      <span class="ticker-section">{{ currentItem.sectionLabel }}:</span>
      {{ currentItem.text }}
    </router-link>
  </div>
</template>

<style scoped>
.global-stats-ticker {
  align-items: center;
  border-top: 1px solid var(--color-border);
  display: flex;
  flex-wrap: wrap;
  gap: 0.45rem;
  justify-content: center;
  margin-top: 0.75rem;
  max-width: 100%;
  padding-top: 0.65rem;
}

.ticker-label {
  background: var(--color-background-soft);
  border: 1px solid var(--color-border);
  border-radius: 4px;
  font-size: 0.85rem;
  font-weight: 700;
  padding: 0.2rem 0.45rem;
  text-transform: uppercase;
}

.ticker-section {
  color: var(--color-text);
  font-weight: 700;
}
</style>
